### ISSUE TITLE
[Bego Ripoll]

### ISSUE THREAD

**Issue by bripollc** [Ironhack-data-bcn-april-2023/project-III-geospatial-data#1]
https://github.com/bripollc/03_Geospatial_data

**Comment by ta-data-bcn** [comment]
Hola Bego!!!
Felicidades por el porject

Un poco de feedback:



**Respecto a la organización del repositorio** 📚

- Nada que decir, ya lo haces perfectamente. 


**El README.md** 📖

- El readme también está perfecto, muy guay que hayas puesto los títulos al principio para poder ir directamente al punto. 
- También el añadir todos los gráficos y conclusiones súper!!!!!

**El código** 👩‍💻

- Estaría bien un main.ipynb donde muestras un poco el trabajo en general!
- Muy bien de utilizar las funciones como has hecho, pero también estaría bien que separaras las funciones en un archivo .py
- No acabo de entender esta frase “we mapped all the locations found for each city using Folium and developed a final weighting table based on the number of locations and their distance to the center.“ Al final de donde has sacado lo weights? De el número de locations que había alrededor?
- Tampoco encuentro en que notebook has hecho estos cálculos
- Por lo demás está muy bien tu código, siempre lo haces simple y fácil de entender, cosa que tus futuros compañeros de trabajo van a agradecer mucho!!!!!!



**Visualización** 🎨

- Las visualizaciones están muy bien Bego! Siempre haces un  workflow que me hace entender perfecto en qué parte de tu proyecto estás cada vez
- La gráfica de los porcentajes no acabo de entender del todo de dónde vienen los datos. 
- Las demás visualizaciones están perfectas! Utilizando markers y circunferencias para mostrar los sitios cercanos y la localización de la nueva oficina.

En general, como tus otros dos proyectos, éste también está 👌👌👌 sigue así Bego!!!!!
Y disfruta tu finde libre!!!!!! 🥳🥳🥳

<img width="557" alt="Screenshot 2023-05-12 at 13 16 06" src="https://github.com/Ironhack-data-bcn-april-2023/project-III-geospatial-data/assets/47005065/a154c338-9df1-4ce0-a93a-36e1d85ad7ee">
