### ISSUE TITLE
PabloCabadas/project-III

### ISSUE THREAD

**Issue by pablocabadas** [Ironhack-data-bcn-april-2023/project-III-geospatial-data#10]
https://github.com/pablocabadas/project-III.git

**Comment by ta-data-bcn** [comment]
Hola Pablo!! 🚀🚀


Antes de todo, felicidades por tu proyecto 💪💪 Aparte de lo que te dijo Fer en la presentación

Un poco de feedback:

**Respecto a la organización del repositorio** 📚

- Intenta siempre meter un .gitignore (de los que propone github al crear el repo), así files no ayudan a tu trabajo como DS_store serán ignorados desde el principio. 
- Buena organización, está en general muy limpio y fácil de entender. Lo único que te diría sería cambiar los nombres de tus notebooks. Ya que uno se llama main y el otro project 3, no sé cual es más importante!
- Por lo demás todo bien!


**El README.md** 📖

- El Readme está muy bien, has explicado bien los goals del proyecto y también las conclusiones.
- Me falta ver un poco de dónde has sacado las decisiones, cómo probar con números que lo que estás haciendo tiene sentido. Por ejemplo, cuando decides las ciudades o cuando decides las áreas, mejor acompañarlo de algún dato específico que explique el porqué de tu decisión!


**El código** 👩‍💻

- Está bien, te faltan muchas funciones!!!! Por ejemplo cuando haces las llamadas a foursquare, son siempre iguales, tu vida sería mucho más fácil si hicieras una función y solo tuvieras que meter las dos cosas que cambian cada vez. 
- Me gustaría ver un poco más de encapsulicazión y modularización! 
- Bien de ir poniendo comentarios a lo largo del código y decir qué es cada cosa, intenta expandir esto un poco más y explicarlo siempre. Por ejemplo (#drawing circles on map, # looking for centre of the circle). ETC
- No entiendo del todo cómo has encontrado los dos puntos rojos!


**Visualización** 🎨

- Las visualizaciones muy bien Pablo!!!!! Igual en vez de heatmaps podrías haber utilizado markers para ver qué tipo de venues hay en qué lugares. 
- Pero en general muy buenos mapas motopapi!!!!


Sigue así, intenta hacer funciones en el próximo project!!!!!!!!!!!!!


<img width="766" alt="Screenshot 2023-05-16 at 09 50 03" src="https://github.com/Ironhack-data-bcn-april-2023/project-III-geospatial-data/assets/47005065/bdb3c638-5a1e-4f44-bb04-108d7debe600">
