### ISSUE TITLE
a bit late

### ISSUE THREAD

**Issue by miguelpalospou** [Ironhack-data-bcn-april-2023/project-III-geospatial-data#11]

**Comment by miguelpalospou** [comment]
https://github.com/miguelpalospou/Project-III-Geo

**Comment by ta-data-bcn** [comment]
Hola Miguel!!!! 👋🏾 


**Respecto a la organización del repositorio** 📚 

- El .gitignore funciona bien e ignora el .env :) 
- Se te ha colado un .DS_Store, intenta ignorarlo la próxima vez.
- Bien organizado el repo también, peeeero te recomiendo guardar tus archivos .py en un folder llamado "src" y los datos en "data"

**El README.md** ✍🏽

- Está bien. Muestras el proceso que seguiste y la justificación de tu decisión de crear la compañía en SF. 
- Te recomiendo explicar un poco más tu metodología en general, y sobret odo hacer una conclusión que acaba de atar un trabajo entero. 
- Igual puedes poner las librerías que usaste y los métodos: Mongo queries, Foursquare API, etc. 

**El código** 👨🏽‍💻

- Bien sacando toda la información de Mongo con queries.
- Las llamadas a la API de Foursquare también están bien. 
- El código en general está muy bien organizado y comentado :) 
- Súper bien poniendo todo tu código en funciones :) aunque cuando comentas lo que hacen tus funciones dentro de ellas, te recomiendo hacerlo con doctrings en vez de con # 's, así 👇🏾

```
def suma(a,b):
'''This functions adds numbers
Args: two int
Returns: one number result of the addition'''
	return a + b
```

- En general el código está bien, está bien la limpieza y la extracción de datos 

**Visualización (mapas)** 🗺 

- Te han quedado muy bien los mapas. Muestran lo que tienen que mostrar para argumentar tu hipótesis✌🏾


En general, está muy bien el proyecto Miguel! 👏🏾 hiciste lo que se pedía y justificaste bien tu decisión de crear la compañía en SF! 

Muchas felicidades y disfruta el finde libre y la boda!

<img width="359" alt="Screenshot 2023-05-12 at 13 26 03" src="https://github.com/Ironhack-data-bcn-april-2023/project-III-geospatial-data/assets/47005065/17d5459f-9307-4136-ac25-aced801c3c90">
