### ISSUE TITLE
Leti_Project_III

### ISSUE THREAD

**Issue by LeticiaIruela** [Ironhack-data-bcn-april-2023/project-III-geospatial-data#2]
https://github.com/LeticiaIruela/Project_III

**Comment by ta-data-bcn** [comment]
Bueeeenas LETI! 🚀🚀


Antes de todo, felicidades por tu proyecto!!!!!!!!!!! Buen trabajo 💪💪
Aparte de lo que comentó Fer en tu presentación, te doy un poco de feedback del proyecto.




**Respecto a la organización del repositorio** 📚

- Está perfecta! Nada que decir!


**El README.md** 📖

- El Readme también está muy bien, has explicado todo lo que has hecho, adjuntado imágenes para acompañar tus explicaciones, has explicado bien tus decisiones.
- La organización del readme también te ha quedado muy bien!

**El código** 👩‍💻

- El código está bien organizado, en funciones y fácil de entender lo que estás haciendo
- Igual podrías hacer una función para no tener que hacer el mismo proceso para cada venue, y solo tener que meter los datos que cambian
- También cuando haces 3 veces lo mismo para ver qué location es mejor, podrías hacer una función que lo dejara más limpio. 
- Muy bien utilizando diccionarios!!


Por ejemplo aquí esas dos funciones hacen lo mismo, why not utilizar la que ya tenías definida de antes?

<img width="620" alt="Screenshot 2023-05-12 at 13 17 53" src="https://github.com/Ironhack-data-bcn-april-2023/project-III-geospatial-data/assets/47005065/392e8296-b68c-4f95-9df7-58b3e94d0f12">


- Por lo demás muy bien ;)

**Visualización** 🎨

- La visualización está muy bien, buen uso de heatmaps para encontrar la zona con mayor número de compañías tech y de diseño.



Sigue así LETI!!!!!!!!!!!! Cuando acabes verás la muchísimo que has aprendido 🙂

<img width="523" alt="Screenshot 2023-05-12 at 13 18 20" src="https://github.com/Ironhack-data-bcn-april-2023/project-III-geospatial-data/assets/47005065/6555b310-2f79-45da-863d-8ddebcdb74a2">
