### ISSUE TITLE
Paula Gonzalez

### ISSUE THREAD

**Issue by pagoba94** [Ironhack-data-bcn-april-2023/project-III-geospatial-data#3]
https://github.com/pagoba94/project3

**Comment by ta-data-bcn** [comment]
Bueeeenas PAULAGG! 🚀🚀


Antes de todo, felicidades por tu proyecto!!!!!!!!!!! Está muy bien, felicidades 💪💪

Un poco de feedback:



**Respecto a la organización del repositorio** 📚

- PERFECTA


**El README.md** 📖

- PERFECTO

**El código** 👩‍💻

- También muy bien, igual si quieres complicarte un poco más podrías haber utilizado geoqueries que lo dimos el viernes. 
- Podrías haber categorizado por barrios, o zonas, etc.
- Podrías haber hecho query de design companies pero con otros keywords parecidos, te habrían salido muchas más!
- Por lo demás la verdad es que me cuesta encontrar algo que corregir! Está muy bien como todos tus trabajos!


**Visualización** 🎨

- Está bien!
- Por ejemplo el gráfico donde hay tantos sitios con 1 (el primero), se puede recortar, ya que mostrar tantos iguales no aporta nada ya que no los vas a analizar. 
- Pie chart topp
- También muy bien por poner markers en los diferentes venues, para mostrar que indeed la ubicación que has escogido cumple con todos los requisitos.
- Podrías haber hecho un heatmap con las companies al principio para ver que zona de la ciudad más te interesaba! Y luego con geoqueries analizar la zona.

Nada más! Muy buen Proyecto again, la verdad me gustaría poder corregirte más cosas pero esque está muy 👌👌👌👌

<img width="501" alt="Screenshot 2023-05-12 at 13 21 35" src="https://github.com/Ironhack-data-bcn-april-2023/project-III-geospatial-data/assets/47005065/8dc39483-e38f-460d-b0f1-89023c1d1afc">
