### ISSUE TITLE
Laura_project3-geospatial

### ISSUE THREAD

**Issue by laumosa** [Ironhack-data-bcn-april-2023/project-III-geospatial-data#6]
https://github.com/laumosa/Project3-geospatial

**Comment by ta-data-bcn** [comment]
Hola Laura!!!
Felicidades por el porject

Un poco de feedback:



**Respecto a la organización del repositorio** 📚 

- No subiste el .env y no se te coló ningún archivo extra al repo, así que perfect :)
- La organización del repo está perfeeecta. 

**El README.md** ✍🏽

- Está súper bien, muy bien explicado. Muestras el proceso que seguiste, las librerías que usaste y la justificación de tu decisión, igual te podrías expresar un poco más en tus decisiones, y sobre todo, tus conclusiones.

**El código** 👨🏽‍💻

- Bien sacando toda la información de Mongo con queries.
- Las llamadas a la API de Foursquare también están bien. 
- El código en general está muy bien organizado y comentado. 
- También muy bien la parte de modularización. 
- ¿Cómo has elegido los weights de cada cosa? Aunque al final sea algo que has decidido tú, podrías explicarlo un poco más
- En las funciones se recomiendo poner doctrings para explicar lo que hace la función y luego algún comentario para especificar cosas: 

```
def suma(a,b):
'''This functions adds numbers
Args: two int
Returns: one number result of the addition'''
	return a + b #b being a constant
```



**Visualización (mapas)** 🗺 

- Buen uso de heatmaps para encontrar la zona con mayor número de compañías tech y de diseño. 
- También muy bien por poner markers en los diferentes venues, para mostrar que indeed la ubicación que escogiste cumple con todos los requisitos. 
- Igual podría haber hecho una con las 5 locations y un plot que ponga cual tiene qué venues más cerca

En general, está súuuuper bien el proyecto Laura! 👏🏾 hiciste lo que se pedía y justificaste bien tus decisiones. Podrías haber mirado también si habían canchas de basket o pet grooming services en el área :)))


Muchas felicidades y disfruuuta el fin de semana de descanso 🚀 

<img width="496" alt="Screenshot 2023-05-12 at 13 52 19" src="https://github.com/Ironhack-data-bcn-april-2023/project-III-geospatial-data/assets/47005065/cf4076a4-1ceb-4fb0-880c-e8426c036466">
