### ISSUE TITLE
Project-3-Ramses

### ISSUE THREAD

**Issue by RamsesMR5** [Ironhack-data-bcn-april-2023/project-III-geospatial-data#8]
https://github.com/RamsesMR5/Project-3.git

**Comment by ta-data-bcn** [comment]
Hola Ram!! 🚀🚀


Antes de todo, felicidades por tu proyecto!!!!!!!!!!! Está muy bien, felicidades 💪💪

Un poco de feedback:


**Respecto a la organización del repositorio** 📚

- Esta bien organizado! Se te ha colado un DS.Store en la página principal que estaría bien quietarlo jeje, por demás está perfecto!!!!!!


**El README.md** 📖

- El Readme… again, intenta hacerlo para el próximo proyecto porque lo tendrás que tener para el final, y así te podré dar un poco de feedback antes de que te metas al final project.


**El código** 👩‍💻

- Respecto al código, muchas felicidades!!! Está súper bien, todo en sus funciones y bien organizado, también vas comentando lo que vas haciendo así que perfect. 
- Recomendaciones: En vez de ponerlo como markdown, las partes largas ponlas en el readme, las explicaciones de cada cosa ponlas en comentario #. Y las explicaciones de las funciones ponlas en docstrings “”” xy ”“”. 
- Esto último igual te ha faltado un poco, una pequeña explicación de lo que hace cada función que has hecho.
- Pero MUY BIEN modularizando todo y metiendolo en archivos .py
- Buen uso de 4square y geojson!!!!!!


**Visualización** 🎨

- No puedo ver ninguno de los gráficos!!!! 
- Creo que no los has guardado, tampoco salen las imágenes del readme!!!!!! Intenta revisar esto cuando puedas.

Buen trabajo RAM!


<img width="462" alt="Screenshot 2023-05-16 at 13 46 32" src="https://github.com/Ironhack-data-bcn-april-2023/project-III-geospatial-data/assets/47005065/695e5eea-5b31-4742-80f1-4e6150a9cbf1">
