### ISSUE TITLE
Jose Marin

### ISSUE THREAD

**Issue by jomape-iron** [Ironhack-data-bcn-april-2023/project-III-geospatial-data#9]
https://github.com/jomape-iron/Project3.git

**Comment by ta-data-bcn** [comment]
Hola JOSE!! 🚀🚀


Antes de todo, felicidades por tu proyecto!!!!!!!!!!! Está muy bien, felicidades 💪💪

Un poco de feedback:



**Respecto a la organización del repositorio** 📚

- Faltan algunas cositas por quitar, como el excel con las ponderaciones que no has utilizado.
- También podrías haber guardado el csv en una carpeta llamada data.
- Por lo demás todo bien!


**El README.md** 📖

- El Readme también está muy bien, has explicado bien los goals del proyecto y también las conclusiones.
- Me falta ver un poco de dónde has sacado las conclusiones, por ejemplo cuando haces el heatmap de todo el mundo, saltas directo a San Francisco, sin explicar el porqué.


**El código** 👩‍💻

- Respecto al código, bien de hacer funciones!! Ahora solo te falta separarlas del notebook y utilizarlas en una versión limpia!
- La función grande que utilizas está pidiendo a gritos que la conviertas en un diccionario!!
- Tus notebooks están muy limpios, y tus funciones bien ejecutadas, podrías explicar mediante docstrings o comentarios lo que hacen exactamente para seguir mejor el hilo de tu proyecto.


**Visualización** 🎨

- Buen uso de heatmaps para encontrar la zona con mayor número de compañías tech y de diseño. 
- También muy bien por poner markers en los diferentes venues, para mostrar que indeed la ubicación que escogiste cumple con todos los requisitos. 

Buen trabajo Jose!! El próximo te va a gustar más seguro ;)!!!!!!
Buen finde libre 

<img width="364" alt="Screenshot 2023-05-12 at 13 33 29" src="https://github.com/Ironhack-data-bcn-april-2023/project-III-geospatial-data/assets/47005065/99b16270-ecd9-42a0-ac75-3092f59d811b">
